app/redhat_insights/default/data/ui/views/main_dashboard.xml

[EVNT-526] Fix Recomendations Search

---

app/redhat_insights/default/data/ui/views/contact_us.xml

`Check integrations in Red Hat Insights`  need to point to:  https://console.redhat.com/beta/settings/integrations

[EVNT-550] Change url on contact us page

---

.github/dependabot.yml
package.json

Adding `package.json` for javascripts dependencies
Now, At 5am UTC, Dependabot will scan your package.json and open a pull request (PR) to merge branch into `master` branch.

[EVNT-258] Adding package.json

---

.github/dependabot.yml

Removing dependabot action

---

app/redhat_insights/default/data/ui/views/events.xml

Remove RHEL bundle to support OCP events (tested!)

Update events.xml to support OpenShift Advisor

---

app/redhat_insights/default/data/ui/views/events.xml

Now that we have openshift bundles in addition to rhel bundles, we need the event header to say System/Cluster instead of only System to be clear.

Update header to System/Cluster

---

.github/workflows/build_splunk_main.yml
.github/workflows/pr_check.yml

This commit add a incrementation on Build number after merge into
`master` and create a new `pull request`

[EVNT-555] Increment Build number

---

examples/patch-example.json
examples/vulnerability-example.json
send-examples.sh

Addin Patch and Vulnerability Examples

[NO-TICKET] Adding Patch and Vulnerability Examples

---

app/redhat_insights/default/data/ui/views/events.xml
app/redhat_insights/default/data/ui/views/main_dashboard.xml

Adding Patch and Vulnerability events into the main dashboard and Events
table
Preview:

[EVNT-623][EVNT-522] Add Patch and Vulnerability

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

Change `Patch` wording on dashboard for app consistency

[EVNT-646] Change Patch wording

---

app/redhat_insights/default/data/ui/views/events.xml

[EVNT-654] Fix Vulnerability description

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

[EVNT-653] Fix vulnerability main dashboard

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

[EVNT-687] Fix pie chart on main dashboard

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

Chagging the time range to grab all day instead just the beggining of the day.

[EVNT-688] Change time range on charts

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

I needed to move the chart a little down, and decrease the chart size.
Preview:

[EVNT-687] Fix chart overlapping issue

---

app/redhat_insights/default/data/ui/views/main_dashboard.xml

This ticket try to solve EVNT-440, EVNT-728 and EVNT-688
Also decrease the height of the chart.
Preview:

[EVNT-440] Fix 30d main dashboard chart

---

app/redhat_insights/default/data/ui/views/events.xml
app/redhat_insights/default/data/ui/views/main_dashboard.xml
examples/ros-example.json
send-examples.sh

Preview:
Events table:
Main dashboard:

[EVNT-708] Onboarding ROS event

---

app/redhat_insights/default/data/ui/views/events.xml

[EVNT-667] Fix null account_id on Patch

---

app/redhat_insights/default/data/ui/views/events.xml

[EVNT-739] Change Org title to Organization

---

app/redhat_insights/appserver/static/javascript/views/app.js
app/redhat_insights/appserver/static/javascript/views/setup.js
app/redhat_insights/appserver/static/javascript/views/setup_configuration.js
app/redhat_insights/appserver/static/javascript/views/splunk_helpers.js

[EVNT-742] Fix setup call after update

---

.github/workflows/build_splunk_main.yml
.github/workflows/pr_check.yml

Fixing github action image since `slim` is not compatible with python >=
3.10

No ticket/fix GitHub actions

---

app/redhat_insights/app.manifest
app/redhat_insights/default/app.conf

feat: Bump v.0.19
